apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-full-cpu
spec:
  selector:
    matchLabels:
      app: myapp
      usage: full-cpu
  template:
    metadata:
      labels:
        app: myapp
        usage: full-cpu
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: myapp
          image: ubuntu:22.04
          args:
            - "dd"
            - "if=/dev/zero"
            - "of=/dev/null"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-no-cpu
spec:
  selector:
    matchLabels:
      app: myapp
      usage: no-cpu
  template:
    metadata:
      labels:
        app: myapp
        usage: no-cpu
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: myapp
          image: ubuntu:22.04
          args:
            - "sleep"
            - "infinity"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
